import Head from 'next/head'
import Header from '../Components/Header'
import Hero from '../Components/Hero'
import HeroAnimation from '../Components/Hero-animation'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Abdullox Next Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
      </Head>
      
      <Header />
      <Hero/>
      <HeroAnimation />

    </div>
  )
}
