import Head from 'next/head'
import Header from '../Components/Header'
// import IntroAudio from "../public/Audio/mp.mp3";

export default function Home() {

  return (
    <div>
      <Head>
        <title>Abdullox Next Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </div>
  )
}
